#!/usr/bin/env bash
# Generate docker/.env for this host.
#
# The group IDs matter: docker-compose's group_add resolves names *inside* the
# container, where `render` usually has a different GID than on the host (or
# does not exist). Passing the host's numeric GIDs is what actually grants the
# container access to /dev/kfd and /dev/dri.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE=docker/.env

VIDEO_GID="$(getent group video  | cut -d: -f3 || echo 44)"
RENDER_GID="$(getent group render | cut -d: -f3 || echo 993)"
UI_PORT="${AI_STUDIO_UI_PORT:-8420}"

if [[ -f "$ENV_FILE" ]] && grep -q '^AI_STUDIO_JOIN_TOKEN=' "$ENV_FILE"; then
  TOKEN="$(grep '^AI_STUDIO_JOIN_TOKEN=' "$ENV_FILE" | cut -d= -f2-)"
  echo "Keeping the existing join token (runners stay connected)."
else
  TOKEN="$(openssl rand -hex 24 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '/+=')"
fi

# GPU architecture for the bitsandbytes source build. Without a match, 4-bit
# quantization is unavailable and large models cannot be shrunk to fit.
ARCH="${BNB_ROCM_ARCH:-}"
if [[ -z "$ARCH" ]] && command -v rocminfo >/dev/null 2>&1; then
  # `|| true` is load-bearing: awk's early `exit` sends SIGPIPE to rocminfo, so
  # under `set -euo pipefail` this assignment would abort the script.
  ARCH="$(rocminfo 2>/dev/null | awk '/gfx/{print $2; exit}' | tr -d ' ' || true)"
fi
ARCH="${ARCH:-gfx1030}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/make-env.sh on $(date -Iseconds)
AI_STUDIO_JOIN_TOKEN=$TOKEN
AI_STUDIO_UI_PORT=$UI_PORT
AI_STUDIO_RUNNER_NAME=$(hostname)
VIDEO_GID=$VIDEO_GID
RENDER_GID=$RENDER_GID
BNB_ROCM_ARCH=$ARCH
# Optional: needed only for gated models such as Llama or Gemma.
HF_TOKEN=${HF_TOKEN:-}
EOF
chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE"
echo "  UI port     : $UI_PORT"
echo "  video GID   : $VIDEO_GID"
echo "  render GID  : $RENDER_GID"
echo "  GPU arch    : $ARCH"
echo "  join token  : $TOKEN"
